package te.app.aljoud.utils;

public class URLS {
//        public final static String BASE_URL = "http://test.joud-edu.com/api/";
    public final static String BASE_URL = "https://joud-edu.com/api/";
    public final static String CONTACT = "store-inbox";
    public final static String HOME = "home/university?page=";
    public final static String UNIVERSITY_DETAILS = "home/university/colleges/";
    public final static String LEVELS = "home/college/levels/";
    public final static String LEVEL_COURSES = "home/level/courses?level_id=";
    public final static String COURSE_DETAILS = "course/details/";
    public final static String COURSE_LESSONS = "course/lessons/";
    public final static String LESSON_VIDEOS = "lesson/videos/";
    public final static String LESSON_QUIZZES = "lesson/quizzes/";
    public final static String LESSON_ARTICLES = "lesson/articles/";
    public final static String RATE_REQUEST = "make/course/rate";
    public final static String ASK_COURSE = "Ask-in-course";
    public final static String ASK_LESSON = "Ask-in-lesson";
    public final static String OFFERS = "offers?page=";
    public final static String BUY_OFFER = "student/buy/offer/";
    public final static String BUY_COURSE = "student/buy/course/";
    public final static String ABOUT = "app/about-us";
    public static final String CHANGE_PROFILE_PASSWORD = "user/change-password";
    public static final String CHANGE_PASSWORD = "password/change";
    public static final String FORGET_PASSWORD = "password/forget";
    public static final String UPDATE_PROFILE = "update/profile";
    public static final String CONFIRM_CODE = "password/verify_code";
    public static final String REGISTER = "sign_up";
    public static final String LOGIN_PASSWORD = "login";
    public static final String CONVERSATIONS = "inboxes?page=";
    public static final String MY_COURSES = "home/my_courses?page=";
    public static final String SERVICES = "helpers/get_services";
    public static final String SEND_SERVICE_REQUEST = "Request-service";
    public static final String CHAT = "replies/";
    public static final String SEND_MESSAGE = "store-reply";
    public static final String QUIZ_LESSON = "quiz/questions/";
    public static final String QUIZ_COURSE = "exam/questions/";
    public static final String PAYMENT_METHODS = "student/buy/course/payment_step_one";
    public static final String CHECK_PAYMENT = "student/buy/course/payment_step_two/";
    public static final String PAYMENT_METHODS_OFFERS = "student/buy/offer/payment_step_one";
    public static final String CHECK_PAYMENT_OFFERS = "student/buy/offer/payment_step_two/";
    public static final String ADD_CART = "student/cart/store";
    public static final String CART_COUNT = "student/cart/count";
    public static final String CART = "student/cart";
    public static final String DELETE_CART_ITEM = "student/cart/remove";
    public static final String APPLY_DISCOUNT = "student/cart/apply/coupon";
    public static final String CHECK_OUT = "student/cart/check_out";

    public static final String GET_CART_INSTALLMENT = "student/cart/get-cart-installments-data";
    public static final String GET_INSTALLMENTS = "student/installments?status=";
    public static final String PAY_INSTALLMENTS = "student/installments/pay";
    public static final String REQUEST_TO_BUY = "student/purchase_requests/store";
}
